"use client";
import {useEffect,useMemo,useState} from "react";

const demo=[
 {id:"wa-demo",channel:"WhatsApp",customer:"New inquiry",externalId:"demo-wa",preview:"Hi, is the black sofa still available?",time:"Just now",unread:true,messages:[{direction:"inbound",text:"Hi, is the black sofa still available?",time:"Just now"},{direction:"inbound",text:"How much is delivery to Kampala?",time:"Just now"}]},
 {id:"fb-demo",channel:"Facebook",customer:"Facebook customer",externalId:"demo-fb",preview:"How much is delivery to Kampala?",time:"8 min ago",unread:true,messages:[{direction:"inbound",text:"How much is delivery to Kampala?",time:"8 min ago"}]}
];

export default function Inbox(){
 const[messages,setMessages]=useState(demo);const[filter,setFilter]=useState("All");const[selected,setSelected]=useState(null);const[reply,setReply]=useState("");const[q,setQ]=useState("");
 useEffect(()=>{fetch("/api/inbox").then(r=>r.json()).then(d=>{if(d.messages?.length)setMessages(d.messages.map(m=>({...m,customer:m.customer||m.customerName,preview:m.preview||m.text,messages:m.messages||[{direction:m.direction||"inbound",text:m.text,time:m.timestamp||"Now"}]})))}).catch(()=>{})},[]);
 const visible=useMemo(()=>messages.filter(m=>(filter==="All"||m.channel===filter)&&`${m.customer} ${m.preview}`.toLowerCase().includes(q.toLowerCase())),[messages,filter,q]);
 const current=messages.find(m=>m.id===selected?.id)||selected;
 function addReply(){if(!reply.trim()||!current)return;setMessages(prev=>prev.map(m=>m.id===current.id?{...m,preview:reply,messages:[...(m.messages||[]),{direction:"outbound",text:reply,time:"Now"}]}:m));setReply("")}
 return <main className="inboxPage"><header className="inboxHeader"><div><div className="eyebrow">TAVQENA INBOX</div><h1>Customer conversations</h1><p>Facebook and WhatsApp messages in one place.</p></div><a className="back" href="/">← Dashboard</a></header><div className="inboxLayout"><aside className="inboxList"><input className="inboxSearch" value={q} onChange={e=>setQ(e.target.value)} placeholder="Search conversations..."/><div className="filters">{["All","WhatsApp","Facebook"].map(x=><button key={x} className={filter===x?"active":""} onClick={()=>setFilter(x)}>{x}</button>)}</div>{visible.map(m=><button className={"thread "+(current?.id===m.id?"selected":"")} key={m.id} onClick={()=>setSelected(m)}><div className="threadTop"><strong>{m.customer}</strong><span>{m.time}</span></div><div className={m.channel==="WhatsApp"?"channel wa":"channel fb"}>{m.channel}</div><p>{m.preview}</p>{m.unread&&<b className="unread">NEW</b>}</button>)}{visible.length===0&&<div className="emptyInbox">No conversations found.</div>}</aside><section className="conversation">{current?<><div className="conversationHead"><div><div className={current.channel==="WhatsApp"?"eyebrow wa":"eyebrow fb"}>{current.channel}</div><h2>{current.customer}</h2><p>{current.externalId}</p></div><button className="profileButton" onClick={()=>alert("Customer profile is linked to the CRM. Open it from the Customers section.")}>Customer profile</button></div><div className="conversationBody">{(current.messages||[{direction:"inbound",text:current.preview,time:current.time}]).map((m,i)=><div className={m.direction==="outbound"?"bubble businessBubble":"bubble customerBubble"} key={i}>{m.text}<small>{m.time}</small></div>)}<div className="insight"><div className="eyebrow">CUSTOMER SIGNAL</div><strong>New customer inquiry</strong><p>This conversation is ready for customer information, pipeline and follow-up.</p></div></div><div className="reply"><textarea value={reply} onChange={e=>setReply(e.target.value)} placeholder="Prepare a reply..."/><div><button className="replyButton" onClick={addReply}>Add reply</button><small>Demo mode — live Meta sending comes after credentials and webhook setup.</small></div></div></>:<div className="emptyConversation"><div className="eyebrow">UNIFIED INBOX</div><h2>Select a conversation</h2><p>Choose a Facebook or WhatsApp message to view it here.</p></div>}</section></div></main>
}
