"use client";
import {useEffect,useState} from "react";

export default function Inbox(){
 const[messages,setMessages]=useState([]); const[filter,setFilter]=useState("All"); const[selected,setSelected]=useState(null); const[reply,setReply]=useState("");
 useEffect(()=>{fetch("/api/inbox").then(r=>r.json()).then(d=>setMessages(d.messages||[])).catch(()=>{})},[]);
 const visible=messages.filter(m=>filter==="All"||m.channel===filter);
 return <main className="inboxPage"><header className="inboxHeader"><div><div className="eyebrow">TAVQENA INBOX</div><h1>Customer conversations</h1><p>Facebook and WhatsApp messages in one place.</p></div><a className="back" href="/">← Dashboard</a></header><div className="inboxLayout"><aside className="inboxList"><div className="filters">{["All","WhatsApp","Facebook"].map(x=><button key={x} className={filter===x?"active":""} onClick={()=>setFilter(x)}>{x}</button>)}</div>{visible.map(m=><button className={"thread "+(selected?.id===m.id?"selected":"")} key={m.id} onClick={()=>setSelected(m)}><div className="threadTop"><strong>{m.customer}</strong><span>{m.time}</span></div><div className="channel">{m.channel}</div><p>{m.preview}</p></button>)}{visible.length===0&&<div className="emptyInbox">No conversations yet.</div>}</aside><section className="conversation">{selected?<><div className="conversationHead"><div><div className="eyebrow">{selected.channel}</div><h2>{selected.customer}</h2></div><span className="live">INBOX</span></div><div className="conversationBody"><div className="bubble customerBubble">{selected.preview}</div><div className="insight"><div className="eyebrow">CUSTOMER SIGNAL</div><strong>New customer inquiry</strong><p>Ready for Tavqena to extract product, price, location and buying intent.</p></div></div><div className="reply"><textarea value={reply} onChange={e=>setReply(e.target.value)} placeholder="Prepare a reply..."/><button onClick={()=>setReply("")}>Prepare reply</button></div></>:<div className="emptyConversation"><div className="eyebrow">UNIFIED INBOX</div><h2>Select a conversation</h2><p>Choose a Facebook or WhatsApp message to view it here.</p></div>}</section></div></main>
}
